SELECT DISTINCT ?composer
  (GROUP_CONCAT (DISTINCT ?name; separator="|") AS ?names)
  (GROUP_CONCAT (DISTINCT ?surname; separator="|") AS ?surnames)
  (COUNT (?expression) AS ?count)
WHERE {
  ?expression a efrbroo:F22_Self-Contained_Expression .
  ?expCreation efrbroo:R17_created ?expression ;
	ecrm:P9_consists_of / ecrm:P14_carried_out_by ?composer .
  ?composer foaf:name ?name .
  ?composer foaf:surname ?surname 
}
GROUP BY ?composer
ORDER BY DESC (?count)